### ISSUE TITLE
Standalone con DTD

### ISSUE THREAD

**Issue by angelodel80** [giacomocerre/codificaEs#1]
Sei sicuro della correttezza dell'attributo standalone quando dichiari una DTD esterna?
```
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 <!DOCTYPE TEI SYSTEM "tei_lite.dtd">
```

**Comment by giacomocerre** [comment]
Giusto, non può starci sto dichiarando appunto un documento esterno.
Grazie mille.
